# Generated by Django 5.2.3 on 2025-08-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinoexercicio',
            name='dia_da_semana',
        ),
        migrations.AddField(
            model_name='treino',
            name='dia_da_semana',
            field=models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='', max_length=10),
        ),
    ]
