# Generated by Django 5.2.3 on 2025-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_aluno_professor_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
